name: Run Pytest
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      mysql-version:
        default: "5.7"
        type: string
      postgres: # todo
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_DATABASE: test
    #       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd="mysqladmin ping -h mysql -u root" --health-interval=20s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{inputs.python-version}}
      - name: Install dependencies
        run: |
          pip install boto3 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: check mysql version
        run: |
          echo "mysql version: $mysql-version"
      - name: wants mysql
        if: ${{inputs.mysql-version}}
        run: |
          echo "should run mysql"
      - name: Setup MySQL DB
        if: ${{inputs.mysql-version}}
        env:
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        run: |
          docker run mysql:${{inputs.mysql-version}} -p 3600:3600 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test -uroot
      - name: Test with pytest
        run: pytest -m "not integration"
